version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dbuser
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      - PMA_HOST=mysql
